<?php

declare(strict_types=1);

use App\Modules\DocumentRequests\Http\Controllers\ShowUploadController;
use App\Modules\Documents\Http\Controllers\ConfirmDocumentUploadController;
use App\Modules\Documents\Http\Controllers\PresignDocumentUploadController;
use Illuminate\Support\Facades\Route;

/**
 * Public upload routes. No auth, no app chrome. Customer arrives here
 * via a link generated by an authed agent (#18).
 */
Route::get('/u/{token}', ShowUploadController::class)->name('uploads.show');

/**
 * Stateless presign endpoint. Auth = the token in the URL itself.
 * CSRF exempt (no session). Throttled per token via the
 * 'upload-presign' rate limiter (see AppServiceProvider).
 */
Route::middleware('throttle:upload-presign')
    ->post('/api/u/{token}/presign', PresignDocumentUploadController::class)
    ->name('uploads.presign');

/**
 * Confirm endpoint — browser POSTs document_ids it just PUT to S3, the
 * server HEAD-verifies each object, marks them confirmed, and locks the
 * session. Same per-token rate limiter as presign.
 */
Route::middleware('throttle:upload-presign')
    ->post('/api/u/{token}/confirm', ConfirmDocumentUploadController::class)
    ->name('uploads.confirm');
